name: Clang

on:
  push:
    paths-ignore:
      - 'sql/**'    
  pull_request:
    paths-ignore:
      - 'sql/**'
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ !github.event.pull_request.draft }}
    steps:
    - uses: actions/checkout@v2
    - name: Dependencies
      run: |
        #ACE
        wget https://github.com/DOCGroup/ACE_TAO/releases/download/ACE%2BTAO-8_0_5/ACE+TAO-8.0.5.tar.gz
        tar xvzf ACE+TAO-8.0.5.tar.gz
        cd ACE_wrappers/
        mkdir build
        cd build
        ../configure --disable-ssl
        make -j4
        make install
     
        # G++
        sudo apt-get install build-essential g++ make cmake git wget libssl-dev libreadline-dev bzip2 libbz2-dev
        sudo apt-get install mysql-server mysql-client libmysqlclient-dev libmysql++-dev
        
        sudo apt install gcc-13 g++-13
        export CXX=g++-13 CC=gcc-13
        
        
    - name: Setup
      run: |
        mkdir bin
        cd bin
        cmake ../ -DTOOLS=1 -DCMAKE_C_COMPILER=/usr/bin/clang -DCMAKE_CXX_COMPILER=/usr/bin/clang++ -DCMAKE_INSTALL_PREFIX=check_install
        cd ..
    - name: Build
      run: |
        mkdir build
        cd build
        cmake ../ -DSCRIPTS=1 -DTOOLS=0 -DCMAKE_BUILD_TYPE=Release
        make -j4
    #- name: Check executables
    #  run: |
    #    cd bin/check_install/bin
    #    ./authserver --version
    #    ./worldserver --version
