name: Clang

on:
  push:
    paths-ignore:
      - 'sql/**'    
  pull_request:
    paths-ignore:
      - 'sql/**'
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
jobs:
  build:
    runs-on: ubuntu-24.04
    if: ${{ !github.event.pull_request.draft }}
    steps:
    - uses: actions/checkout@v2
    - name: Dependencies
      run: |
        # G++
        sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
       
        # MySQL
        sudo rm -rf /var/lib/dpkg/lock
        sudo wget https://dev.mysql.com/get/mysql-apt-config_0.8.29-1_all.deb
        sudo dpkg -i mysql-apt-config_0.8.29-1_all.deb
        
        sudo apt update
        sudo apt-get update
        
        sudo apt-get install openssl libssl-dev
       
        sudo apt-get install -y build-essential libstdc++-14-dev gcc-14 g++-14 autoconf libtool make cmake git-core patch wget links zip unzip unrar libmysqlclient-dev libmysql++-dev libreadline6-dev zlib1g-dev libbz2-dev libncurses5-dev libace-dev
        
        sudo apt install gcc-13 g++-13
        export CXX=g++-13 CC=gcc-13
        
        sudo apt-get install libncurses5-dev libace-dev
        sudo apt-get install build-essential autoconf libtool make cmake git-core patch wget links zip unzip unrar
        sudo apt-get install libmysqlclient-dev libmysql++-dev libreadline6-dev zlib1g-dev libbz2-dev
    - name: Setup
      run: |
        mkdir bin
        cd bin
        cmake ../ -DTOOLS=1 -DCMAKE_C_COMPILER=/usr/bin/clang -DCMAKE_CXX_COMPILER=/usr/bin/clang++ -DCMAKE_INSTALL_PREFIX=check_install
        cd ..
    - name: Build
      run: |
        mkdir build
        cd build
        cmake ../ -DSCRIPTS=1 -DTOOLS=0 -DCMAKE_BUILD_TYPE=Release
        make -j4
    #- name: Check executables
    #  run: |
    #    cd bin/check_install/bin
    #    ./authserver --version
    #    ./worldserver --version
